table DimProduct
	lineageTag: 7a0d0a67-aeff-4cca-986d-1cc6b687e980

	column ProductKey
		dataType: string
		lineageTag: 0f8c201b-b6cc-4a6c-b3f0-c9d21ef819b9
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: b85709af-d488-4fb6-a8dd-56ca1a299622
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Subcategory
		dataType: string
		lineageTag: f4363eff-343b-452a-a7bc-5e96092e6dfa
		summarizeBy: none
		sourceColumn: Subcategory

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: f70d0a90-db60-496c-88fa-dc8ff710f98e
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	partition DimProduct = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("F:\BI\retail-bi-project\data\DimProduct.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductKey", type text}, {"Category", type text}, {"Subcategory", type text}, {"ProductName", type text}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

