table DimRegion
	lineageTag: fd3cb2ac-a1ce-4eb4-ba23-4c770ae7ac66

	column RegionID
		dataType: string
		lineageTag: f6d67c7f-9238-47b3-a6ac-4996d115cf94
		summarizeBy: none
		sourceColumn: RegionID

		annotation SummarizationSetBy = Automatic

	column RegionName
		dataType: string
		lineageTag: 481cfbfd-73b0-4aeb-923f-3693956aa4ae
		summarizeBy: none
		sourceColumn: RegionName

		annotation SummarizationSetBy = Automatic

	partition DimRegion = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("F:\BI\retail-bi-project\data\DimRegion.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"RegionID", type text}, {"RegionName", type text}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

